inherit_from:
  - 'https://raw.githubusercontent.com/feracommerce/code-standards/master/.rubocop.yml'
inherit_mode:
    merge:
      - Exclude
AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - '*.gem'
